In [46]:
import numpy as np
import pandas as pd
arr1=np.arange(10)
print(arr1)


[0 1 2 3 4 5 6 7 8 9]


In [47]:
print(type(arr1))

<class 'numpy.ndarray'>


In [48]:
s1=pd.Series(arr1)
print(s1)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32


In [49]:
print(type(s1))

<class 'pandas.core.series.Series'>


In [50]:
dic1={'a':10,'b':20,'c':30,'d':40,'e':50}
print(dic1)
print(type(dic1))

{'a': 10, 'b': 20, 'c': 30, 'd': 40, 'e': 50}
<class 'dict'>


In [51]:
s2=pd.Series(dic1)
s2
print(type(s2))

<class 'pandas.core.series.Series'>


In [52]:
arr2=np.array(np.arange(12)).reshape(4,3)
print(arr2)
print(type(arr2))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
<class 'numpy.ndarray'>


In [53]:
df1=pd.DataFrame(arr2)
print(df1)
print(type(df1))

   0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11
<class 'pandas.core.frame.DataFrame'>


In [54]:
dic2={'a':[1,2,3,4],'b':[5,6,7,8],'c':[9,10,11,12],'d':[13,14,15,16]}
print(dic2)
print(type(dic2))

{'a': [1, 2, 3, 4], 'b': [5, 6, 7, 8], 'c': [9, 10, 11, 12], 'd': [13, 14, 15, 16]}
<class 'dict'>


In [55]:
df2=pd.DataFrame(dic2)
print(df2)
print(type(df2))

   a  b   c   d
0  1  5   9  13
1  2  6  10  14
2  3  7  11  15
3  4  8  12  16
<class 'pandas.core.frame.DataFrame'>


In [56]:
dic3={'one':{'a':1,'b':2,'c':3,'d':4},'two':{'a':5,'b':6,'c':7,'d':8},'three':{'a':9,'b':10,'c':11,'d':12}}
print(dic3)
print(type(dic3))

{'one': {'a': 1, 'b': 2, 'c': 3, 'd': 4}, 'two': {'a': 5, 'b': 6, 'c': 7, 'd': 8}, 'three': {'a': 9, 'b': 10, 'c': 11, 'd': 12}}
<class 'dict'>


In [57]:
df3=pd.DataFrame(dic3)
print(df3)
print(type(df3))

   one  two  three
a    1    5      9
b    2    6     10
c    3    7     11
d    4    8     12
<class 'pandas.core.frame.DataFrame'>


In [58]:
df4=df3[['one','three']]
print(df4)
print(type(df4))

   one  three
a    1      9
b    2     10
c    3     11
d    4     12
<class 'pandas.core.frame.DataFrame'>


In [59]:
s3=df3['one']
print(s3)
print(type(s3))

a    1
b    2
c    3
d    4
Name: one, dtype: int64
<class 'pandas.core.series.Series'>


In [60]:
s4=pd.Series(np.array([1,1,2,3,5,8]))
print(s4)

0    1
1    1
2    2
3    3
4    5
5    8
dtype: int32


In [61]:
print(s4.index)

RangeIndex(start=0, stop=6, step=1)


In [62]:
s4.index=['a','b','c','d','e','f']
print(s4)

a    1
b    1
c    2
d    3
e    5
f    8
dtype: int32


In [63]:
print(s4[3])

3


In [64]:
print(s4['e'])

5


In [65]:
s4[[1,3,5]]

b    1
d    3
f    8
dtype: int32

In [66]:
s5 = pd.Series(np.array([10,15,20,30,55,80]),index = ['a','b','c','d','e','f'])
print(s5)

s6 = pd.Series(np.array([12,11,13,15,14,16]),index = ['a','c','g','b','d','f'])
print(s6)

a    10
b    15
c    20
d    30
e    55
f    80
dtype: int32
a    12
c    11
g    13
b    15
d    14
f    16
dtype: int32


In [67]:
print(s5+s6)

a    22.0
b    30.0
c    31.0
d    44.0
e     NaN
f    96.0
g     NaN
dtype: float64


In [1]:
import pandas as pd

stu_dic = {'Age':[14,13,13,14,14,12,12,15,13,12,11,14,12,15,16,12,15,11,15],
'Height':[69,56.5,65.3,62.8,63.5,57.3,59.8,62.5,62.5,59,51.3,64.3,56.3,66.5,72,64.8,67,57.5,66.5],
'Name':['Alfred','Alice','Barbara','Carol','Henry','James','Jane','Janet','Jeffrey','John','Joyce','Judy','Louise','Marry','Philip','Robert','Ronald','Thomas','Willam'],
'Sex':['M','F','F','F','M','M','F','F','M','M','F','F','F','F','M','M','M','M','M'],
'Weight':[112.5,84,98,102.5,102.5,83,84.5,112.5,84,99.5,50.5,90,77,112,150,128,133,85,112]}

In [4]:
student=pd.DataFrame(stu_dic)

In [5]:
student.head()

Age  Height     Name Sex  Weight
0   14    69.0   Alfred   M   112.5
1   13    56.5    Alice   F    84.0
2   13    65.3  Barbara   F    98.0
3   14    62.8    Carol   F   102.5
4   14    63.5    Henry   M   102.5

In [6]:
student.describe()

Age     Height      Weight
count  19.000000  19.000000   19.000000
mean   13.315789  62.336842  100.026316
std     1.492672   5.127075   22.773933
min    11.000000  51.300000   50.500000
25%    12.000000  58.250000   84.250000
50%    13.000000  62.800000   99.500000
75%    14.500000  65.900000  112.250000
max    16.000000  72.000000  150.000000

In [71]:
student.tail()

Age  Height    Name Sex  Weight
14   16    72.0  Philip   M   150.0
15   12    64.8  Robert   M   128.0
16   15    67.0  Ronald   M   133.0
17   11    57.5  Thomas   M    85.0
18   15    66.5  Willam   M   112.0

In [72]:
student.loc[[0,2,4,5,7]]

Age  Height     Name Sex  Weight
0   14    69.0   Alfred   M   112.5
2   13    65.3  Barbara   F    98.0
4   14    63.5    Henry   M   102.5
5   12    57.3    James   M    83.0
7   15    62.5    Janet   F   112.5

In [73]:
student[['Name','Height','Weight']].head()

Name  Height  Weight
0   Alfred    69.0   112.5
1    Alice    56.5    84.0
2  Barbara    65.3    98.0
3    Carol    62.8   102.5
4    Henry    63.5   102.5

In [74]:
student['Name'].head()

0     Alfred
1      Alice
2    Barbara
3      Carol
4      Henry
Name: Name, dtype: object

In [75]:
student.loc[:,['Name','Height','Weight']].head()

Name  Height  Weight
0   Alfred    69.0   112.5
1    Alice    56.5    84.0
2  Barbara    65.3    98.0
3    Carol    62.8   102.5
4    Henry    63.5   102.5

In [76]:
student[(student["Sex"]=='F')&(student['Age']>12)]

Age  Height     Name Sex  Weight
1    13    56.5    Alice   F    84.0
2    13    65.3  Barbara   F    98.0
3    14    62.8    Carol   F   102.5
7    15    62.5    Janet   F   112.5
11   14    64.3     Judy   F    90.0
13   15    66.5    Marry   F   112.0

In [77]:
np.random.seed(1234)

In [78]:
d1=pd.Series(2*np.random.normal(size=100)+3)
d2=np.random.f(2,4,size=100)
d3=np.random.randint(1,100,size=100)
d3

array([55, 68, 73, 59, 60, 57, 73, 14, 38,  8, 10, 74, 65,  9, 37, 15, 93,
       70, 54, 83, 63, 30, 71, 68, 65, 89, 18, 87, 27, 31, 49, 20,  8, 43,
       76, 43, 86, 91, 13, 97, 73, 26, 89, 92, 60, 76, 50, 91, 45, 53, 44,
       67, 23, 20, 11, 88, 52, 12, 19, 73, 86, 67, 21, 11, 62,  9, 86, 67,
       20, 48, 14, 72, 67, 23, 93, 82,  3, 85, 91, 46, 30, 72, 51, 60, 11,
       25, 52, 70, 25,  6, 36, 38, 46, 68,  6, 55, 98, 98, 59, 36])

In [79]:
print('10%分位数：',d1.quantile(0.1))

10%分位数： 0.6870184644069928


In [80]:
df=pd.DataFrame(np.array([d1,d2,d3]).T,columns=['x1','x2','x3'])
print(df.head())

         x1        x2    x3
0  3.942870  1.369531  55.0
1  0.618049  0.943264  68.0
2  5.865414  0.590663  73.0
3  2.374696  0.206548  59.0
4  1.558823  0.223204  60.0


In [81]:
def stats(x):
	return pd.Series([x.count(),x.min(),x.idxmin(),x.quantile(.25),x.median(),x.quantile(.75),
                      x.mean(),x.max(),x.idxmax(),x.mad(),x.var(),x.std(),x.skew(),x.kurt()],
                     index = ['Count','Min','Whicn_Min','Q1','Median','Q3','Mean','Max',
                              'Which_Max','Mad','Var','Std','Skew','Kurt'])
print(stats(d1))

Count        100.000000
Min           -4.127033
Whicn_Min     81.000000
Q1             2.040101
Median         3.204555
Q3             4.434788
Mean           3.070225
Max            7.781921
Which_Max     39.000000
Mad            1.511288
Var            4.005609
Std            2.001402
Skew          -0.649478
Kurt           1.220109
dtype: float64


In [82]:
df.apply(stats)

x1          x2          x3
Count      100.000000  100.000000  100.000000
Min         -4.127033    0.014330    3.000000
Whicn_Min   81.000000   72.000000   76.000000
Q1           2.040101    0.249580   25.000000
Median       3.204555    1.000613   54.500000
Q3           4.434788    2.101581   73.000000
Mean         3.070225    2.028608   51.490000
Max          7.781921   18.791565   98.000000
Which_Max   39.000000   53.000000   96.000000
Mad          1.511288    1.922669   24.010800
Var          4.005609   10.206447  780.090808
Std          2.001402    3.194753   27.930106
Skew        -0.649478    3.326246   -0.118917
Kurt         1.220109   12.636286   -1.211579

In [83]:
student['Sex'].describe()

count     19
unique     2
top        M
freq      10
Name: Sex, dtype: object

In [84]:
df.corr()

x1        x2        x3
x1  1.000000  0.136085  0.037185
x2  0.136085  1.000000 -0.005688
x3  0.037185 -0.005688  1.000000

In [85]:
dic={'Name':['LiuShunxiang','Zhangshan'],
    'Sex':['M','F'],
    'Age':[27,23],
    'Height':[165.7,167.2],
    'Weight':[61,63]}
student2=pd.DataFrame(dic)
student2

Name Sex  Age  Height  Weight
0  LiuShunxiang   M   27   165.7      61
1     Zhangshan   F   23   167.2      63

In [86]:
student3=pd.concat([student,student2])
print(student3)

    Age  Height          Name Sex  Weight
0    14    69.0        Alfred   M   112.5
1    13    56.5         Alice   F    84.0
2    13    65.3       Barbara   F    98.0
3    14    62.8         Carol   F   102.5
4    14    63.5         Henry   M   102.5
5    12    57.3         James   M    83.0
6    12    59.8          Jane   F    84.5
7    15    62.5         Janet   F   112.5
8    13    62.5       Jeffrey   M    84.0
9    12    59.0          John   M    99.5
10   11    51.3         Joyce   F    50.5
11   14    64.3          Judy   F    90.0
12   12    56.3        Louise   F    77.0
13   15    66.5         Marry   F   112.0
14   16    72.0        Philip   M   150.0
15   12    64.8        Robert   M   128.0
16   15    67.0        Ronald   M   133.0
17   11    57.5        Thomas   M    85.0
18   15    66.5        Willam   M   112.0
0    27   165.7  LiuShunxiang   M    61.0
1    23   167.2     Zhangshan   F    63.0


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [87]:
pd.DataFrame(student2,columns=['Age','Height','Name','Sex','Weight','Score'])

Age  Height          Name Sex  Weight  Score
0   27   165.7  LiuShunxiang   M      61    NaN
1   23   167.2     Zhangshan   F      63    NaN

In [88]:
del student2

In [89]:
student.drop([0,1,3,6])

Age  Height     Name Sex  Weight
2    13    65.3  Barbara   F    98.0
4    14    63.5    Henry   M   102.5
5    12    57.3    James   M    83.0
7    15    62.5    Janet   F   112.5
8    13    62.5  Jeffrey   M    84.0
9    12    59.0     John   M    99.5
10   11    51.3    Joyce   F    50.5
11   14    64.3     Judy   F    90.0
12   12    56.3   Louise   F    77.0
13   15    66.5    Marry   F   112.0
14   16    72.0   Philip   M   150.0
15   12    64.8   Robert   M   128.0
16   15    67.0   Ronald   M   133.0
17   11    57.5   Thomas   M    85.0
18   15    66.5   Willam   M   112.0

In [90]:
student[student['Age']>14]

Age  Height    Name Sex  Weight
7    15    62.5   Janet   F   112.5
13   15    66.5   Marry   F   112.0
14   16    72.0  Philip   M   150.0
16   15    67.0  Ronald   M   133.0
18   15    66.5  Willam   M   112.0

In [91]:
student.drop(['Height','Weight'],axis=1).head()

Age     Name Sex
0   14   Alfred   M
1   13    Alice   F
2   13  Barbara   F
3   14    Carol   F
4   14    Henry   M

In [92]:
student3.loc[student3['Name']=='LiuShunxiang','Height']=173
student3[student3['Name']=='LiuShunxiang'][['Name','Height']]

Name  Height
0  LiuShunxiang   173.0

In [93]:
print(student.groupby('Sex').mean())

           Age     Height      Weight
Sex                                  
F    13.222222  60.588889   90.111111
M    13.400000  63.910000  108.950000


In [94]:
student.drop('Age',axis=1).groupby('Sex').mean()

Height      Weight
Sex                       
F    60.588889   90.111111
M    63.910000  108.950000

In [95]:
student.groupby(['Sex','Age']).mean()

Height  Weight
Sex Age                   
F   11   51.300000   50.50
    12   58.050000   80.75
    13   60.900000   91.00
    14   63.550000   96.25
    15   64.500000  112.25
M   11   57.500000   85.00
    12   60.366667  103.50
    13   62.500000   84.00
    14   66.250000  107.50
    15   66.750000  122.50
    16   72.000000  150.00

In [96]:
student.drop('Age',axis=1).groupby('Sex').agg([np.mean,np.median])

Height             Weight        
          mean median        mean  median
Sex                                      
F    60.588889  62.50   90.111111   90.00
M    63.910000  64.15  108.950000  107.25

In [97]:
Data=pd.Series(np.array(np.random.randint(1,20,10)))
Data

0    18
1    15
2    16
3    18
4    16
5     8
6    17
7    10
8    16
9     6
dtype: int32

In [98]:
Data.sort_index()

0    18
1    15
2    16
3    18
4    16
5     8
6    17
7    10
8    16
9     6
dtype: int32

In [99]:
Data.sort_values(ascending=False)

3    18
0    18
6    17
8    16
4    16
2    16
1    15
7    10
5     8
9     6
dtype: int32

In [100]:
student.sort_values(by=['Age','Height'])

Age  Height     Name Sex  Weight
10   11    51.3    Joyce   F    50.5
17   11    57.5   Thomas   M    85.0
12   12    56.3   Louise   F    77.0
5    12    57.3    James   M    83.0
9    12    59.0     John   M    99.5
6    12    59.8     Jane   F    84.5
15   12    64.8   Robert   M   128.0
1    13    56.5    Alice   F    84.0
8    13    62.5  Jeffrey   M    84.0
2    13    65.3  Barbara   F    98.0
3    14    62.8    Carol   F   102.5
4    14    63.5    Henry   M   102.5
11   14    64.3     Judy   F    90.0
0    14    69.0   Alfred   M   112.5
7    15    62.5    Janet   F   112.5
13   15    66.5    Marry   F   112.0
18   15    66.5   Willam   M   112.0
16   15    67.0   Ronald   M   133.0
14   16    72.0   Philip   M   150.0

In [101]:
dic2 = {'Name':['Alfred','Alice','Barbara','Carol','Henry','Jeffrey','Judy','Philip','Robert','Willam'],
        'Score':[88,76,89,67,79,90,92,86,73,77]}
score=pd.DataFrame(dic2)

In [102]:
score

Name  Score
0   Alfred     88
1    Alice     76
2  Barbara     89
3    Carol     67
4    Henry     79
5  Jeffrey     90
6     Judy     92
7   Philip     86
8   Robert     73
9   Willam     77

In [103]:
student

Age  Height     Name Sex  Weight
0    14    69.0   Alfred   M   112.5
1    13    56.5    Alice   F    84.0
2    13    65.3  Barbara   F    98.0
3    14    62.8    Carol   F   102.5
4    14    63.5    Henry   M   102.5
5    12    57.3    James   M    83.0
6    12    59.8     Jane   F    84.5
7    15    62.5    Janet   F   112.5
8    13    62.5  Jeffrey   M    84.0
9    12    59.0     John   M    99.5
10   11    51.3    Joyce   F    50.5
11   14    64.3     Judy   F    90.0
12   12    56.3   Louise   F    77.0
13   15    66.5    Marry   F   112.0
14   16    72.0   Philip   M   150.0
15   12    64.8   Robert   M   128.0
16   15    67.0   Ronald   M   133.0
17   11    57.5   Thomas   M    85.0
18   15    66.5   Willam   M   112.0

In [104]:
stu_score1=pd.merge(student,score,on='Name')
stu_score1

Age  Height     Name Sex  Weight  Score
0   14    69.0   Alfred   M   112.5     88
1   13    56.5    Alice   F    84.0     76
2   13    65.3  Barbara   F    98.0     89
3   14    62.8    Carol   F   102.5     67
4   14    63.5    Henry   M   102.5     79
5   13    62.5  Jeffrey   M    84.0     90
6   14    64.3     Judy   F    90.0     92
7   16    72.0   Philip   M   150.0     86
8   12    64.8   Robert   M   128.0     73
9   15    66.5   Willam   M   112.0     77

In [105]:
stu_score2=pd.merge(student,score,on='Name',how='left')
stu_score2

Age  Height     Name Sex  Weight  Score
0    14    69.0   Alfred   M   112.5   88.0
1    13    56.5    Alice   F    84.0   76.0
2    13    65.3  Barbara   F    98.0   89.0
3    14    62.8    Carol   F   102.5   67.0
4    14    63.5    Henry   M   102.5   79.0
5    12    57.3    James   M    83.0    NaN
6    12    59.8     Jane   F    84.5    NaN
7    15    62.5    Janet   F   112.5    NaN
8    13    62.5  Jeffrey   M    84.0   90.0
9    12    59.0     John   M    99.5    NaN
10   11    51.3    Joyce   F    50.5    NaN
11   14    64.3     Judy   F    90.0   92.0
12   12    56.3   Louise   F    77.0    NaN
13   15    66.5    Marry   F   112.0    NaN
14   16    72.0   Philip   M   150.0   86.0
15   12    64.8   Robert   M   128.0   73.0
16   15    67.0   Ronald   M   133.0    NaN
17   11    57.5   Thomas   M    85.0    NaN
18   15    66.5   Willam   M   112.0   77.0

In [106]:
s=stu_score2['Score']

In [107]:
s

0     88.0
1     76.0
2     89.0
3     67.0
4     79.0
5      NaN
6      NaN
7      NaN
8     90.0
9      NaN
10     NaN
11    92.0
12     NaN
13     NaN
14    86.0
15    73.0
16     NaN
17     NaN
18    77.0
Name: Score, dtype: float64

In [108]:
print(sum(pd.isnull(s)))

9


In [109]:
s.dropna()

0     88.0
1     76.0
2     89.0
3     67.0
4     79.0
8     90.0
11    92.0
14    86.0
15    73.0
18    77.0
Name: Score, dtype: float64

In [112]:
df=pd.DataFrame([[1,1,2],[3,5,np.nan],[13,21,34],[55,np.nan,10],[np.nan,np.nan,np.nan],[np.nan,1,2]],columns=('x1','x2','x3'))
print(df)

     x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0   NaN
2  13.0  21.0  34.0
3  55.0   NaN  10.0
4   NaN   NaN   NaN
5   NaN   1.0   2.0


In [114]:
df.dropna(how='all')

x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0   NaN
2  13.0  21.0  34.0
3  55.0   NaN  10.0
5   NaN   1.0   2.0

In [115]:
df.fillna(0)

x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0   0.0
2  13.0  21.0  34.0
3  55.0   0.0  10.0
4   0.0   0.0   0.0
5   0.0   1.0   2.0

In [116]:
df.fillna(method='ffill')

x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0   2.0
2  13.0  21.0  34.0
3  55.0  21.0  10.0
4  55.0  21.0  10.0
5  55.0   1.0   2.0

In [117]:
df.fillna(method='bfill')

x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0  34.0
2  13.0  21.0  34.0
3  55.0   1.0  10.0
4   NaN   1.0   2.0
5   NaN   1.0   2.0

In [118]:
print(df.fillna({'x1':1,'x2':2,'x3':3}))

     x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0   3.0
2  13.0  21.0  34.0
3  55.0   2.0  10.0
4   1.0   2.0   3.0
5   1.0   1.0   2.0


In [119]:
x1_median=df['x1'].mean()
x2_median=df['x2'].mean()
x3_median=df['x3'].mean()

print(x1_median,x2_median,x3_median)

18.0 7.0 12.0


In [121]:
df.fillna({'x1':x1_median,'x2':x2_median,'x3':x3_median})

x1    x2    x3
0   1.0   1.0   2.0
1   3.0   5.0  12.0
2  13.0  21.0  34.0
3  55.0   7.0  10.0
4  18.0   7.0  12.0
5  18.0   1.0   2.0

In [124]:
Tabel=pd.pivot_table(student,values=['Height'],columns=['Sex'])
Tabel

Sex             F      M
Height  60.588889  63.91

In [125]:
Tabel2=pd.pivot_table(student,values=['Height','Weight'],columns=['Sex'])
Tabel2

Sex             F       M
Height  60.588889   63.91
Weight  90.111111  108.95

In [126]:
Tabel3=pd.pivot_table(student,values=['Height','Weight'],columns=['Sex','Age'])
Tabel3

        Sex  Age
Height  F    11      51.300000
             12      58.050000
             13      60.900000
             14      63.550000
             15      64.500000
        M    11      57.500000
             12      60.366667
             13      62.500000
             14      66.250000
             15      66.750000
             16      72.000000
Weight  F    11      50.500000
             12      80.750000
             13      91.000000
             14      96.250000
             15     112.250000
        M    11      85.000000
             12     103.500000
             13      84.000000
             14     107.500000
             15     122.500000
             16     150.000000
dtype: float64

In [127]:
Tabel4=pd.pivot_table(student,values=['Height','Weight'],columns=['Sex','Age']).unstack()
Tabel4

Age           11          12    13      14      15     16
       Sex                                               
Height F    51.3   58.050000  60.9   63.55   64.50    NaN
       M    57.5   60.366667  62.5   66.25   66.75   72.0
Weight F    50.5   80.750000  91.0   96.25  112.25    NaN
       M    85.0  103.500000  84.0  107.50  122.50  150.0

In [128]:
s=pd.Series(np.arange(1,10),index=[['a','a','a','b','b','c','c','d','d'],[1,2,3,1,2,3,1,2,3]])
s
                                    

a  1    1
   2    2
   3    3
b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int32

In [129]:
s.index

MultiIndex(levels=[['a', 'b', 'c', 'd'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [130]:
print(s['a'])

1    1
2    2
3    3
dtype: int32


In [131]:
print(s['a',1])

1


In [139]:
print(s['a'],1)

1    1
2    2
3    3
dtype: int32 1


In [140]:
print(s[['a','c']])

a  1    1
   2    2
   3    3
c  3    6
   1    7
dtype: int32


In [141]:
print(s['b':'d'])

b  1    4
   2    5
c  3    6
   1    7
d  2    8
   3    9
dtype: int32


In [142]:
print(s.unstack())

     1    2    3
a  1.0  2.0  3.0
b  4.0  5.0  NaN
c  7.0  NaN  6.0
d  NaN  8.0  9.0


In [143]:
data=pd.DataFrame(np.random.randint(0,150,size=(8,12)),
                 columns=pd.MultiIndex.from_product([['模拟考','正式考'],
                                                    ['math','chinese','english','physical','chemsical','bio']]),
                 index=pd.MultiIndex.from_product([['mid','final'],
                                                  ['leijun','libing'],
                                                 ['test one','test two']]))
data

模拟考                                          正式考  \
                      math chinese english physical chemsical  bio math   
mid   leijun test one  138      57      24        3        77    0  131   
             test two   53      47      48      123        61   57   32   
      libing test one    6      58      42       98        65   31  115   
             test two  121      69     100       47        46   11   85   
final leijun test one  126      18     127       15        79  131    1   
             test two   44      79      86       86       129  116   51   
      libing test one   67      30       8      125       115   48  134   
             test two   75      16     123      115        76    9   64   

                                                               
                      chinese english physical chemsical  bio  
mid   leijun test one     116     149        0        66  136  
             test two     139      62       22         7   59  
      libing test one     109      24       83         3  101  
             test two      41       5       37        12  144  
final leijun test one      73      72      104        48   56  
             test two       5      85      148       137  138  
      libing test one     120      51      115        98   59  
             test two     148      77      126        49   94

In [144]:
data['模拟考'][['chinese','math']]

chinese  math
mid   leijun test one       57   138
             test two       47    53
      libing test one       58     6
             test two       69   121
final leijun test one       18   126
             test two       79    44
      libing test one       30    67
             test two       16    75

In [148]:
data.loc['mid','leijun','test one']['模拟考','math']

138

In [151]:
data.loc['mid','leijun','test one']

模拟考  math         138
     chinese       57
     english       24
     physical       3
     chemsical     77
     bio            0
正式考  math         131
     chinese      116
     english      149
     physical       0
     chemsical     66
     bio          136
Name: (mid, leijun, test one), dtype: int32

In [152]:
data.loc[['mid','leijun','test one']]

模拟考                                         正式考          \
                    math chinese english physical chemsical bio math chinese   
mid leijun test one  138      57      24        3        77   0  131     116   
           test two   53      47      48      123        61  57   32     139   
    libing test one    6      58      42       98        65  31  115     109   
           test two  121      69     100       47        46  11   85      41   

                                                     
                    english physical chemsical  bio  
mid leijun test one     149        0        66  136  
           test two      62       22         7   59  
    libing test one      24       83         3  101  
           test two       5       37        12  144

In [153]:
data.iloc[0]

模拟考  math         138
     chinese       57
     english       24
     physical       3
     chemsical     77
     bio            0
正式考  math         131
     chinese      116
     english      149
     physical       0
     chemsical     66
     bio          136
Name: (mid, leijun, test one), dtype: int32

In [154]:
data['正式考']

math  chinese  english  physical  chemsical  bio
mid   leijun test one   131      116      149         0         66  136
             test two    32      139       62        22          7   59
      libing test one   115      109       24        83          3  101
             test two    85       41        5        37         12  144
final leijun test one     1       73       72       104         48   56
             test two    51        5       85       148        137  138
      libing test one   134      120       51       115         98   59
             test two    64      148       77       126         49   94